// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7koORXw2AEOWuz0gK1U0MQWXaEj5f3u4',
    appId: '1:404691657162:web:32b964959b077114d72f33',
    messagingSenderId: '404691657162',
    projectId: 'realtime-database-e48e2',
    authDomain: 'realtime-database-e48e2.firebaseapp.com',
    databaseURL: 'https://realtime-database-e48e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-e48e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbVJPpFZhYYYjKgjcfcvEWyhGFT8y5qI',
    appId: '1:404691657162:android:69c35c30b7bd8b8bd72f33',
    messagingSenderId: '404691657162',
    projectId: 'realtime-database-e48e2',
    databaseURL: 'https://realtime-database-e48e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-e48e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyDEoJqAtzGjyPZ7RkPu5BL_fKG6QNZk',
    appId: '1:404691657162:ios:67bed7648be209b3d72f33',
    messagingSenderId: '404691657162',
    projectId: 'realtime-database-e48e2',
    databaseURL: 'https://realtime-database-e48e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-e48e2.firebasestorage.app',
    androidClientId: '404691657162-n1nm6cv8b838rbrpacs0lp14jpfakuo7.apps.googleusercontent.com',
    iosClientId: '404691657162-iaftjdunaheacb950kc8bfiuj22k2932.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyDEoJqAtzGjyPZ7RkPu5BL_fKG6QNZk',
    appId: '1:404691657162:ios:67bed7648be209b3d72f33',
    messagingSenderId: '404691657162',
    projectId: 'realtime-database-e48e2',
    databaseURL: 'https://realtime-database-e48e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-e48e2.firebasestorage.app',
    androidClientId: '404691657162-n1nm6cv8b838rbrpacs0lp14jpfakuo7.apps.googleusercontent.com',
    iosClientId: '404691657162-iaftjdunaheacb950kc8bfiuj22k2932.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7koORXw2AEOWuz0gK1U0MQWXaEj5f3u4',
    appId: '1:404691657162:web:33056ac37a768dcfd72f33',
    messagingSenderId: '404691657162',
    projectId: 'realtime-database-e48e2',
    authDomain: 'realtime-database-e48e2.firebaseapp.com',
    databaseURL: 'https://realtime-database-e48e2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-database-e48e2.firebasestorage.app',
  );
}
